services:
  app:
    build: ./notifications-backend
    ports:
      - "8080:8080"
    environment:
      DATASOURCES_DEFAULT_URL: jdbc:postgresql://db:5432/notifications_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: notification_postgres
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: