micronaut.application.name=notification
micronaut.server.port=8080

datasources.default.url=jdbc:postgresql://localhost:5432/notifications_db
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.username=user
datasources.default.password=password
datasources.default.dialect=POSTGRES

flyway.datasources.default.enabled=true
flyway.datasources.default.locations=classpath:db/migration

jpa.default.properties.hibernate.hbm2ddl.auto=validate
jpa.default.properties.hibernate.show_sql=true
jpa.default.properties.hibernate.format_sql=true