# APP
micronaut.application.name=notification
micronaut.server.port=8080

# DB
datasources.default.url=jdbc:postgresql://localhost:5432/notifications_db
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.username=user
datasources.default.password=password
datasources.default.dialect=POSTGRES
flyway.datasources.default.enabled=true
flyway.datasources.default.locations=classpath:db/migration
jpa.default.properties.hibernate.hbm2ddl.auto=validate
jpa.default.properties.hibernate.format_sql=true

# BENCHMARK
jpa.default.properties.hibernate.show_sql=false
jpa.default.properties.hibernate.jdbc.batch_size=100
jpa.default.properties.hibernate.order_inserts=true
jpa.default.properties.hibernate.order_updates=true
seeder.enabled=true
seeder.users.count=1000

# AWS
aws.region=us-east-1
aws.sqs.enabled=true
aws.access-key-id=ntd
aws.secret-key=ntd
aws.services.sqs.endpoint=http://notification-localstack:4566
notifications.queue.name=notifications_queue

# JMS
micronaut.jms.sqs.enabled=true

# SEC
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins=http://localhost:3000
micronaut.server.cors.configurations.dev.allowed-methods=POST,PUT,GET,DELETE,OPTIONS,HEAD
micronaut.server.cors.configurations.dev.allowed-headers=Content-Type,Authorization,X-Requested-With,Accept,Origin
micronaut.server.cors.configurations.dev.allow-credentials=true
micronaut.server.cors.configurations.dev.max-age=3600